### ISSUE TITLE
Code examples didn't work

### ISSUE THREAD

**Issue by doverradio** [eeshi/node-scrapy#22]
Hi, I just tried to run the code examples in a newly initialized directory and got this output:

```
k# node 0test.js
/root/node-scrapy-examples/0test.js:5
scrapy.scrape(url, selector, function(err, data) {
       ^

TypeError: scrapy.scrape is not a function
    at Object.<anonymous> (/root/node-scrapy-examples/0test.js:5:8)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by stefanmaric** [comment]
Hi @doverradio 

Thanks for reporting the issue.

The main branch (master, at that time) was pointing to the legacy version.

I've changed the main branch, updated some dependencies, updated the README examples to work with the latest Github UI, and published a new version.

Please give the new examples a try and let me know if works now.

**Comment by mariusa** [comment]
README Example works for me
